### ISSUE TITLE
GT和DT框的编码方式怎么不一样啊？anchor的生成不带角度吗？ IOU匹配为什么不使用rbbox_IOU

### ISSUE THREAD

**Issue by APeiZou** [Capino512/pytorch-rotation-decoupled-detector#2]

**Comment by Capino512** [comment]
疑问三连让我很头大啊>_<
1. xywh的编码方式跟现有水平框的编码方法是一样的，自己理解下啦。角度编码就是把它们都处理成-1到1的值。
2. anchor可以理解成不带角度的矩形，也可以理解成带角度的(0°和90度)。
3. GT解耦得到的HBB跟不带角度的anchor匹配，用bbox_IoU就OK啦。

**Comment by APeiZou** [comment]
您好，基于darknet53模型训练好的权重有提供吗？

**Comment by Capino512** [comment]
没有，只是前期用darknet53做过测试

**Comment by APeiZou** [comment]
训练HRSC2016的代码骨干网络换成darknet53的时候报这种错怎么解决啊
Traceback (most recent call last):
  File "/data/project_all/pytorch-rotation-decoupled-detector-master/run/hrsc2016/train.py", line 143, in <module>
    main()
  File "/data/project_all/pytorch-rotation-decoupled-detector-master/run/hrsc2016/train.py", line 86, in main
    model.init()
  File "/data/project_all/pytorch-rotation-decoupled-detector-master/models/rdd/rdd.py", line 67, in init
    self.backbone.init()
  File "/data/project_all/pytorch-rotation-decoupled-detector-master/models/backbone/darknet.py", line 54, in init
    weight = torch.load(weights[self.name])
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by Capino512** [comment]
不清楚，确认下去权重文件是否完整，也可能是版本问题

**Comment by kuazhangxiaoai** [comment]
> 疑问三连让我很头大啊>_<
> 
> 1. xywh的编码方式跟现有水平框的编码方法是一样的，自己理解下啦。角度编码就是把它们都处理成-1到1的值。
> 2. anchor可以理解成不带角度的矩形，也可以理解成带角度的(0°和90度)。
> 3. GT解耦得到的HBB跟不带角度的anchor匹配，用bbox_IoU就OK啦。

1、请问，您将GT解耦成两种，0-45度的GT对应0度anchor，45-90对应成90度的anchor，对吗？
2、您论文上不是写使用30度间隔的oriented anchors吗？
![image](https://user-images.githubusercontent.com/54108453/128155973-d2af56d0-b2dc-4b4b-8904-584b05a24885.png)

**Comment by Capino512** [comment]
1.-45度到+45度GT对应0度anchor, 45度-135度GT对应90度的anchor.
2.30度间隔的oriented anchors是模拟已有基于多角度anchor算法的匹配过程时用到的.

**Comment by Fly-dream12** [comment]
Can you explain how the figure5 in paper (The comparison between the strategy based on oriented anchors and the proposed strategy) is ploted?  @Capino512  Thanks!

**Comment by Capino512** [comment]
> Can you explain how the figure5 in paper (The comparison between the strategy based on oriented anchors and the proposed strategy) is ploted? @Capino512 Thanks!

First, for an N*N feature map, we respectively generated the anchors required for the two strategies. Second, for a given ground truth box (GT), we changed the aspect/angle of the GT, calculated the IoU between GT and anchors, and judge whether they match according to the IoU. Finally, we plotted the statistical results in python.
