### ISSUE TITLE
[rbbox_overlap_gpu installation] TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by sandeepnmenon** [Capino512/pytorch-rotation-decoupled-detector#9]
While running ```python setup.py build_ext --inplace``` from ```$PATH_ROOT/utils/box/ext/rbbox_overlap_gpu```
I am getting the following error
```
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    setup(
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 57, in __init__
    super().__init__(filtered)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
    ordered = sorted(eps, key=by_group)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/menonsandu/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/home/menonsandu/anaconda3/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```

**Comment by chenchen98752** [comment]
![image](https://user-images.githubusercontent.com/103397044/201805894-63efc0db-a531-478d-9408-0acea71ff798.png)
![image](https://user-images.githubusercontent.com/103397044/201805926-2bed8d85-f116-470b-8280-2af7edfac590.png)
请问作者 这个.py文件不存在 只有.pyx  这个错误怎么解决呢

**Comment by Capino512** [comment]
没有.py文件，编译成功会生成.pyd或.so文件，把它放在.pyx同级目录下就行

**Comment by chenchen98752** [comment]
请问您说的编译该怎么编译 试了好多 不太行 是用setup.py打包吗

**Comment by Capino512** [comment]
首页[compile](https://github.com/Capino512/pytorch-rotation-decoupled-detector#compile)部分有介绍，编译gpu版本需要安装cuda并正确配置环境变量
